RIDE_ACTIVE = "active"
RIDE_CANCELLED = "cancelled"
RIDE_COMPLETED = "completed"

BOOKING_PENDING = "pending"
BOOKING_ACCEPTED = "accepted"
BOOKING_PAID = "paid"
BOOKING_REJECTED = "rejected"
BOOKING_CANCELLED = "cancelled"
BOOKING_COMPLETED = "completed"
BOOKING_EXPIRED = "expired"

PAYMENT_PENDING = "pending"
PAYMENT_SUCCEEDED = "succeeded"
PAYMENT_COMPLETED = PAYMENT_SUCCEEDED
PAYMENT_FAILED = "failed"
PAYMENT_CANCELLED = "cancelled"
PAYMENT_REFUNDED = "refunded"

RIDE_STATUSES = {RIDE_ACTIVE, RIDE_CANCELLED, RIDE_COMPLETED}
BOOKING_STATUSES = {
    BOOKING_PENDING,
    BOOKING_ACCEPTED,
    BOOKING_PAID,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    BOOKING_COMPLETED,
    BOOKING_EXPIRED,
}
PAYMENT_STATUSES = {
    PAYMENT_PENDING,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_CANCELLED,
    PAYMENT_REFUNDED,
}

_RIDE_TRANSITIONS = {
    RIDE_ACTIVE: {RIDE_CANCELLED, RIDE_COMPLETED},
    RIDE_CANCELLED: set(),
    RIDE_COMPLETED: set(),
}

_BOOKING_TRANSITIONS = {
    BOOKING_PENDING: {BOOKING_ACCEPTED, BOOKING_REJECTED, BOOKING_CANCELLED},
    BOOKING_ACCEPTED: {BOOKING_PAID, BOOKING_CANCELLED, BOOKING_EXPIRED},
    BOOKING_PAID: {BOOKING_CANCELLED, BOOKING_COMPLETED},
    BOOKING_REJECTED: set(),
    BOOKING_CANCELLED: set(),
    BOOKING_COMPLETED: set(),
    BOOKING_EXPIRED: set(),
}

_PAYMENT_TRANSITIONS = {
    PAYMENT_PENDING: {PAYMENT_SUCCEEDED, PAYMENT_FAILED, PAYMENT_CANCELLED},
    PAYMENT_SUCCEEDED: {PAYMENT_REFUNDED},
    PAYMENT_FAILED: set(),
    PAYMENT_CANCELLED: set(),
    PAYMENT_REFUNDED: set(),
}


def can_transition_ride(current: str, target: str) -> bool:
    return target in _RIDE_TRANSITIONS.get(current, set())


def can_transition_booking(current: str, target: str) -> bool:
    return target in _BOOKING_TRANSITIONS.get(current, set())


def can_transition_payment(current: str, target: str) -> bool:
    return target in _PAYMENT_TRANSITIONS.get(current, set())
