import { apiAdminService } from '@/services/api/api-admin-service';
import { apiAuthService } from '@/services/api/api-auth-service';
import { apiBookingsService } from '@/services/api/api-bookings-service';
import { apiMessagesService } from '@/services/api/api-messages-service';
import { apiPaymentsService } from '@/services/api/api-payments-service';
import { apiReviewsService } from '@/services/api/api-reviews-service';
import { apiTripsService } from '@/services/api/api-trips-service';
import { apiGamificationService } from '@/services/api/api-gamification-service';
import type { AdminService } from '@/services/contracts/admin-service';
import type { AuthService } from '@/services/contracts/auth-service';
import type { BookingsService } from '@/services/contracts/bookings-service';
import type { MessagesService } from '@/services/contracts/messages-service';
import type { PaymentsService } from '@/services/contracts/payments-service';
import type { ReviewsService } from '@/services/contracts/reviews-service';
import type { TripsService } from '@/services/contracts/trips-service';
import type { GamificationService } from '@/services/contracts/gamification-service';

export const authService: AuthService = apiAuthService;
export const tripsService: TripsService = apiTripsService;
export const bookingsService: BookingsService = apiBookingsService;
export const reviewsService: ReviewsService = apiReviewsService;
export const adminService: AdminService = apiAdminService;
export const messagesService: MessagesService = apiMessagesService;
export const paymentsService: PaymentsService = apiPaymentsService;
export const gamificationService: GamificationService = apiGamificationService;
