"""add_payment_deadline

Revision ID: 182515a3b882
Revises: f2d4c6a8b901
Create Date: 2026-06-09 17:27:51.817969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '182515a3b882'
down_revision: Union[str, None] = 'f2d4c6a8b901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('payment_deadline', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'payment_deadline')
    # ### end Alembic commands ###
