"""Add verification fields to Vehicle

Revision ID: 29713c6a61f9
Revises: d7e8f9a0b1c2
Create Date: 2026-06-19 15:42:08.821929

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "29713c6a61f9"
down_revision: Union[str, None] = "d7e8f9a0b1c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicles",
        sa.Column(
            "verification_status",
            sa.String(length=20),
            server_default="unverified",
            nullable=False,
        ),
    )
    op.add_column(
        "vehicles", sa.Column("document_url", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicles", "document_url")
    op.drop_column("vehicles", "verification_status")
    # ### end Alembic commands ###
