"""Add is_email_verified to user

Revision ID: 5cd61f94c01b
Revises: c16a2f8bfc99
Create Date: 2026-05-28 02:36:47.914663

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "5cd61f94c01b"
down_revision: Union[str, None] = "c16a2f8bfc99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_email_verified", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_email_verified")
    # ### end Alembic commands ###
