"""Add seats_count and variations to vehicles

Revision ID: 5e2bf617a145
Revises: a5e6f7b8c9d0
Create Date: 2026-06-19 14:23:23.729251

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "5e2bf617a145"
down_revision: Union[str, None] = "a5e6f7b8c9d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "rides", ["share_token"])
    op.add_column(
        "vehicles",
        sa.Column("seats_count", sa.Integer(), server_default="4", nullable=False),
    )
    op.add_column(
        "vehicles", sa.Column("variations", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicles", "variations")
    op.drop_column("vehicles", "seats_count")
    op.drop_constraint(None, "rides", type_="unique")  # type: ignore
    # ### end Alembic commands ###
