"""add_performance_indexes

Revision ID: b36aff3634ba
Revises: 182515a3b882
Create Date: 2026-06-10 01:26:10.524522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b36aff3634ba'
down_revision: Union[str, None] = '182515a3b882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bookings_passenger_id', 'bookings', ['passenger_id'], unique=False)
    op.create_index('ix_bookings_ride_id', 'bookings', ['ride_id'], unique=False)
    op.create_index('ix_rides_departure_time', 'rides', ['departure_time'], unique=False)
    op.create_index('ix_rides_driver_id', 'rides', ['driver_id'], unique=False)
    op.create_index('ix_rides_status', 'rides', ['status'], unique=False)
    op.create_index('ix_vehicles_user_id', 'vehicles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicles_user_id', table_name='vehicles')
    op.drop_index('ix_rides_status', table_name='rides')
    op.drop_index('ix_rides_driver_id', table_name='rides')
    op.drop_index('ix_rides_departure_time', table_name='rides')
    op.drop_index('ix_bookings_ride_id', table_name='bookings')
    op.drop_index('ix_bookings_passenger_id', table_name='bookings')
    # ### end Alembic commands ###
