"""add email to users

Revision ID: c16a2f8bfc99
Revises: c53c6572ad92
Create Date: 2026-05-28 01:23:12.073168

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "c16a2f8bfc99"
down_revision: Union[str, None] = "c53c6572ad92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
