"""add_verification_fields

Revision ID: e5c1a8d9b2f3
Revises: d2a9f1b8c3e4
Create Date: 2026-05-19 23:41:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5c1a8d9b2f3"
down_revision: Union[str, None] = "d2a9f1b8c3e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "verification_status",
            sa.String(length=20),
            server_default="none",
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("document_url", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "document_url")
    op.drop_column("users", "verification_status")
    # ### end Alembic commands ###
