

export const ROUTES = {
  home: '/',
  register: '/auth/register',
  login: '/auth/login',
  profileSetup: '/profile/setup',
  profile: '/profile',
  search: '/trips',
  trips: '/trips',
  tripDetails: (id: string) => `/trips/${id}`,
  bookings: '/bookings',
  bookingRequests: '/bookings/requests',
  driverDashboard: '/driver',
  driverApply: '/driver/apply',
  createTrip: '/driver/create-trip',
  myTrips: '/driver/my-trips',
  driverRequests: '/driver/requests',
  driverVehicle: '/driver/vehicle',
  driverDocuments: '/driver/documents',
  createReview: '/reviews/create',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminTrips: '/admin/trips',
  adminBookings: '/admin/bookings',
  adminVerifications: '/admin/verifications',
} as const;
